# Generated by Django 4.2.4 on 2023-09-05 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user_id',
        ),
    ]
