# Generated by Django 4.2.4 on 2023-09-05 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_rename_user_id_chat_user_remove_account_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
        migrations.AddField(
            model_name='account',
            name='user_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chat',
            name='acc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bot.account'),
        ),
    ]
