# Generated by Django 4.2.4 on 2023-09-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_rename_acc_chat_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_name',
            field=models.TextField(blank=True),
        ),
    ]
