# Generated by Django 4.2.4 on 2023-09-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='negative',
            field=models.TextField(blank=True),
        ),
    ]
